#!/bin/bash

create_version_h() {
	local dir="$1"
	local branch="$2"
	local Main_Version="$3"
	local SourceRevision="$4"

	local VersionName="$Main_Version$(date -u +%Y%m%d%H%M)+$SourceRevision"
	local CompileDate="$(date)"

	cat <<-EOF > "$dir/$branch/src/version.h"
		// Do NOT edit this file, it is automatically generated prior to build.
		#ifndef VERSION
		#define VERSION "$VersionName"
		#endif

		#ifndef LMCE_version_h
		#define LMCE_version_h
		// In source files stored in archives and packages, these 2 lines will have the release version (build)
		// and the svn revision as a global variable that can be inspected within a core dump
		#ifdef EXTERN_REVISION_DATE
		extern const char *g_szCompile_Date;
		extern const char *g_szSourceRevision;
		#else
		const char *g_szCompile_Date="$CompileDate";
		const char *g_szSourceRevision="$SourceRevision";
		#endif
		#endif
		EOF
}
